import { registerSW } from "virtual:pwa-register";

/**
 * Registers the service worker generated by vite-plugin-pwa.
 * `autoUpdate` means a new version activates automatically on the next load,
 * so the person is never stuck on a stale cached version.
 */
export function setupPWA() {
  if ("serviceWorker" in navigator) {
    registerSW({ immediate: true });
  }
}
